name: Wiki update
on:
    push:
        paths:
            - 'wiki/**'
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: example
                access_token: ${{ secrets.GITHUB_TOKEN }}
                wiki_folder: wiki
                commit_username: 'Captcardoso'
                commit_email: 'cardosoafolabi@yahoo.com'
                commit_message: 'action: wiki sync'